[package]
name = "ogrim-shared"
version = "0.0.1"
authors = ["Aleksey Zholobenko <aleshaleksey@googlemail.com>"]
edition = "2021"
rust-version = "1.72" # Likely not required. Latest Rust version on initial release.
